### PR TITLE
Use pip version to receive latest image

### PR DESCRIPTION
**Pull request by edlerd**
Avoid using snap version which is out of date, replace it with the pip version which will pull in the latest updates.

### CODE REVIEW

**Review by mas-who — APPROVED** [review]

**Review by bartaz — APPROVED** [review]
LGTM

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Comment by bartaz** [comment]
It seems we don't have write access to this repo, and it's requires review from someone with write access:

image

**Comment by edlerd** [comment]
> It seems we don't have write access to this repo, and it's requires review from someone with write access:

I requested to add our web and design GitHub groups to be added as maintainers, which IS did just recently, so we can merge it now. Thanks for the reviews :)

**Pull request merged**
